"""add videos table

Revision ID: a9f4ec130b8b
Revises: a96294ca354c
Create Date: 2023-09-01 19:19:29.285847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9f4ec130b8b'
down_revision: Union[str, None] = 'a96294ca354c'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('3divi_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PROCESS', 'PAUSE', 'READY', 'RESUME', name='facerecognitionstatusenum'), nullable=True),
    sa.Column('frame', sa.Integer(), nullable=True),
    sa.Column('persons', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('3divi_videos')
    # ### end Alembic commands ###
